# Generated by Django 2.1.1 on 2018-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_brand',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
