# Generated by Django 2.1.1 on 2018-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_shop_brand_is_working'),
    ]

    operations = [
        migrations.CreateModel(
            name='addr_handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recv_name', models.CharField(max_length=10)),
                ('recv_tel', models.CharField(max_length=11)),
                ('recv_addr', models.CharField(max_length=30)),
            ],
        ),
    ]
