# Generated by Django 2.1.1 on 2018-10-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_addr_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='addr_handler',
            name='basic_tel',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
