# Generated by Django 2.1.1 on 2018-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20181005_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='date',
            field=models.DateTimeField(max_length=20),
        ),
    ]
