# Generated by Django 2.1.1 on 2018-10-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20181005_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicTel', models.CharField(max_length=20)),
                ('resName', models.CharField(max_length=20)),
                ('resType', models.CharField(max_length=20)),
                ('resLevel', models.CharField(max_length=20)),
                ('resImg', models.CharField(max_length=20)),
            ],
        ),
    ]
