# Generated by Django 2.1.1 on 2018-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='resImg',
            field=models.CharField(max_length=100),
        ),
    ]
