# Generated by Django 2.1.1 on 2018-10-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20181005_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect',
            name='collect_status',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
