# Generated by Django 2.1.1 on 2018-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_collect_collect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_brand',
            name='shop_tel',
            field=models.CharField(default=None, max_length=11),
            preserve_default=False,
        ),
    ]
