# Generated by Django 2.1.1 on 2018-10-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_shop_brand_shop_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop_brand',
            name='shop_tel',
        ),
    ]
