# Generated by Django 2.1.1 on 2018-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishName', models.CharField(max_length=50)),
                ('dishValue', models.FloatField(max_length=10)),
                ('dishPath', models.CharField(max_length=100)),
            ],
        ),
    ]
