# Generated by Django 2.1.1 on 2018-10-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemCountValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basicTel', models.CharField(max_length=11)),
                ('dishName', models.CharField(max_length=50)),
                ('dishNum', models.IntegerField(max_length=20)),
                ('dishValue', models.FloatField(max_length=50)),
            ],
        ),
    ]
