# Generated by Django 2.1.1 on 2018-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_temcountvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temcountvalue',
            name='dishValue',
            field=models.CharField(max_length=50),
        ),
    ]
